# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
